import Head from "next/head";
import React from "react";
import styles from '../../styles/LeaderBoard.module.css'

const LeaderBoard = () => {
  return (
    <div>
      <Head>
        <title>Whack A Mole</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default LeaderBoard;
