import Head from 'next/head'
import React from 'react'
import styles from '../../styles/Game.module.css'

const Game = () => {
  return (
    <div>
      <Head>
        <title>Whack A Mole</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default Game