import Head from 'next/head'
import styles from '../styles/StartPage.module.css';
import { useRouter } from 'next/router';

const StartPage = () => {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Start Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <h1 className={styles.title}>Whack A Mole</h1>
        <button className={styles.startBtn} onClick={() => router.push('/whack-a-mole')}>START</button>
      </main>
    </div>
  )
}

export default StartPage;